spring:
  mail:
    host: smtp.wp.pl
    username: email-testowy2@wp.pl
    password: ^/3.MPpa+#(QyEy
    port: 465
    properties:
      mail.smtp.ssl.enable: true
      smtp:
        auth=true
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:friendoo
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  sql:
    init:
      mode: never
  profiles:
    default: dev





